export const JobMock = [
  {
    jobId: 'job11',
    title: 'Backend Developer',
    companyId: 'comp7',
    companyProfileImage: '',
    location: 'Boston, MA',
    description: 'Build and maintain scalable server-side applications.',
    salaryRange: '$95,000 - $140,000',
    employmentType: 'Full-time',
    applicationDeadline: '2023-12-31',
    postedDate: '2023-10-15',
    skills: ['Python', 'Django', 'PostgreSQL'],
    experienceLevel: 'Mid-level',
    benefits: ['Health insurance', 'Stock options', 'Flexible hours'],
  },
  {
    jobId: 'job12',
    title: 'Product Manager',
    companyId: 'comp8',
    companyProfileImage: '',
    location: 'Remote',
    description: 'Define product vision and lead development teams.',
    salaryRange: '$110,000 - $160,000',
    employmentType: 'Full-time',
    applicationDeadline: '2023-12-01',
    postedDate: '2023-10-12',
    skills: ['Product Management', 'Agile', 'Stakeholder Communication'],
    experienceLevel: 'Senior',
    benefits: ['Remote work', 'Health insurance', '401k'],
  },
  {
    jobId: 'job13',
    title: 'UX Designer',
    companyId: 'comp9',
    companyProfileImage: '',
    location: 'San Diego, CA',
    description: 'Design intuitive and user-friendly interfaces.',
    salaryRange: '$75,000 - $110,000',
    employmentType: 'Full-time',
    applicationDeadline: '2023-11-30',
    postedDate: '2023-10-11',
    skills: ['Figma', 'Wireframing', 'User Research'],
    experienceLevel: 'Mid-level',
    benefits: ['Health insurance', 'Paid time off'],
  },
  {
    jobId: 'job14',
    title: 'Cybersecurity Analyst',
    companyId: 'comp7',
    companyProfileImage: '',
    location: 'Washington, DC',
    description: 'Protect our systems from cyber threats and vulnerabilities.',
    salaryRange: '$90,000 - $130,000',
    employmentType: 'Full-time',
    applicationDeadline: '2023-12-15',
    postedDate: '2023-10-13',
    skills: ['Cybersecurity', 'Penetration Testing', 'SIEM'],
    experienceLevel: 'Senior',
    benefits: ['Health insurance', 'Remote work options', '401k'],
  },
  {
    jobId: 'job15',
    title: 'Mobile App Developer',
    companyId: 'comp10',
    companyProfileImage: '',
    location: 'Denver, CO',
    description: 'Develop high-quality mobile applications for iOS and Android.',
    salaryRange: '$85,000 - $125,000',
    employmentType: 'Contract',
    applicationDeadline: '2023-11-25',
    postedDate: '2023-10-14',
    skills: ['Flutter', 'Dart', 'REST APIs'],
    experienceLevel: 'Mid-level',
    benefits: ['Contract bonuses', 'Flexible hours'],
  },
  {
    jobId: 'job16',
    title: 'Social Media Coordinator',
    companyId: 'comp8',
    companyProfileImage: '',
    location: 'Remote',
    description: 'Manage social media accounts and create engaging content.',
    salaryRange: '$45,000 - $70,000',
    employmentType: 'Part-time',
    applicationDeadline: '2023-12-05',
    postedDate: '2023-10-16',
    skills: ['Social Media', 'Content Creation', 'Analytics'],
    experienceLevel: 'Entry-level',
    benefits: ['Remote work', 'Flexible hours'],
  },
  {
    jobId: 'job17',
    title: 'Financial Analyst',
    companyId: 'comp11',
    companyProfileImage: '',
    location: 'Houston, TX',
    description: 'Analyze financial data to support business strategies.',
    salaryRange: '$70,000 - $100,000',
    employmentType: 'Full-time',
    applicationDeadline: '2023-12-10',
    postedDate: '2023-10-17',
    skills: ['Excel', 'Financial Modeling', 'Data Analysis'],
    experienceLevel: 'Mid-level',
    benefits: ['Health insurance', '401k', 'Paid time off'],
  },
  {
    jobId: 'job18',
    title: 'Technical Writer',
    companyId: 'comp9',
    companyProfileImage: '',
    location: 'Remote',
    description: 'Create clear and concise technical documentation.',
    salaryRange: '$50,000 - $80,000',
    employmentType: 'Freelance',
    applicationDeadline: '2023-11-20',
    postedDate: '2023-10-18',
    skills: ['Technical Writing', 'Documentation', 'Communication'],
    experienceLevel: 'Mid-level',
  },
  {
    jobId: 'job19',
    title: 'Machine Learning Engineer',
    companyId: 'comp12',
    companyProfileImage: '',
    location: 'Palo Alto, CA',
    description: 'Develop and deploy machine learning models.',
    salaryRange: '$120,000 - $180,000',
    employmentType: 'Full-time',
    applicationDeadline: '2023-12-20',
    postedDate: '2023- ',
    skills: ['Python', 'TensorFlow', 'Machine Learning'],
    experienceLevel: 'Senior',
    benefits: ['Stock options', 'Health insurance', 'Remote work options'],
  },
  {
    jobId: 'job20',
    title: 'Recruiter',
    companyId: 'comp10',
    companyProfileImage: '',
    location: 'Phoenix, AZ',
    description: 'Source and hire top talent for our organization.',
    salaryRange: '$60,000 - $90,000',
    employmentType: 'Full-time',
    applicationDeadline: '2023-12-01',
    postedDate: '2023-10-20',
    skills: ['Recruitment', 'Interviewing', 'HR'],
    experienceLevel: 'Entry-level',
    benefits: ['Health insurance', 'Paid time off'],
  },
];
